### ISSUE TITLE
Possible Invalid PDF for Runtime Polymorphism Talk?

### ISSUE THREAD

**Issue by JaapSuter** [CppCon/CppCon2017#1]
Hello,

At least on my machine, when I visit https://github.com/CppCon/CppCon2017/blob/master/Presentations/Runtime%20Polymorphism%20-%20Back%20to%20Basics/Runtime%20Polymorphism%20-%20Back%20to%20Basics%20-%20Louis%20Dionne%20-%20CppCon%202017.pdf, the given PDF is actually a 766 line HTML file (which Github subsequently fails to render as a PDF as one might expect :) ). In said HTML, there's a link to a PDF on Louis Dionne's own Github (@ldionne), which I imagine is the one that should be available from this repo as well:

    https://github.com/ldionne/cppcon-2017-runtime-polymorphism/blob/gh-pages/slides.pdf

Cheers,

Jaap Suter

**Comment by kernhanda** [comment]
Fixed. Thanks for letting us know.
