### ISSUE TITLE
missing Naked Coroutines Live slides

### ISSUE THREAD

**Issue by cmonagh** [CppCon/CppCon2017#4]
@GorNishanov :sob:

**Comment by GorNishanov** [comment]
Don't have push access. Available here at the moment: https://github.com/GorNishanov/await/raw/master/2017_CppCon/Naked%20Coroutines%20Live%20-%20Gor%20Nishanov%20-%20CppCon%202017.pdf

**Comment by hanickadot** [comment]
@GorNishanov just send them here: speaker-files@cppcon.org

**Comment by GorNishanov** [comment]
I did :-). Maybe script does not like me. Or if it is manually added, it has not been added yet.

**Comment by kernhanda** [comment]
Added with ddda9f76c0c55936988011a6bbc02dec80ef6e3a
