### ISSUE TITLE
Cannot find Bryce Lelbach’s 2-part talk

### ISSUE THREAD

**Issue by will-crawford** [CppCon/CppCon2017#6]
Full title:
> C++17 FEATURES  
> AN INTRODUCTION TO C++17 VIA INSPIRING EXAMPLES

He has the slides on github.io, so not a complete obstacle, but it's a tad disconcerting that the boilerplate CppCon intro under the youtube video begins:

> Presentation Slides, PDFs, Source Code and other presenter materials are available at: https://github.com/CppCon/CppCon2017

**Comment by kernhanda** [comment]
@brycelelbach can you send the slides in pdf/ppt format to speaker-files@cppcon.org?

**Comment by johnmcfarlane** [comment]
Bryce gave much [the same talk at CppNow](https://www.youtube.com/watch?v=LvwXJjRQfHk). Here are the CppNow slides in [pdf form](https://github.com/boostcon/cppnow_presentations_2017/blob/master/05-16-2017_tuesday/cpp17_features__bryce_adelstein_lelbach__cppnow_05-16-2017.pdf) and [browser-friendly version](https://brycelelbach.github.io/cpp17_features/).

**Comment by will-crawford** [comment]
With apologies, I see it is listed in the README with a link to @brycelelbach 's own github pages; I was looking in the repository. Local error :)
